[env:esp32-s3-devkitc-1]
platform       = espressif32
board          = esp32-s3-devkitc-1
framework      = arduino
monitor_speed  = 115200

lib_deps =
    openagriculturefoundation/rosserial_arduino@0.0.0-alpha+sha.1834b766b0
    https://github.com/basicmicro/roboclaw_arduino_library.git
    adafruit/Adafruit NeoPixel@^1.12.4

build_flags =
    -DCONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ=240
    -DCONFIG_PM_ENABLE=1
    -DCONFIG_PM_DFS_INIT_AUTO=1
    -DCONFIG_FREERTOS_UNICORE=1
    -DCONFIG_FREERTOS_HZ=1000
    -DCONFIG_MBEDTLS_HARDWARE_AES=1
    -DCONFIG_MBEDTLS_HARDWARE_SHA=1
    -DCONFIG_LWIP_IPV6=0
    -DCONFIG_LOG_DEFAULT_LEVEL=2
    -DCONFIG_ESP_TASK_WDT_PANIC=0
    -DCONFIG_FREERTOS_CHECK_PORT_CRITICAL_COMPLIANCE=0
    -DCONFIG_FREERTOS_CHECK_MUTEX_GIVEN_BY_OWNER=0
    -O2

